### ISSUE TITLE
Please provide help on how to install on Ubuntu

### ISSUE THREAD

**Issue by yubrshen** [matthiasn/meins#22]
After I download the file meins-0.6.80.dmg
I tried and searched around, but could not figure out how to install the software. 

I tried to mount it, but it seems that the file is compressed. I couldn't. 

I tried to convert it to .img file by dmg2img, but I found that it would restore to a disk, looks too dangerous to do.

**Comment by matthiasn** [comment]
Hi Yu, the DMG file is a disk image that can be mounted on a Mac. For Ubuntu, you need an AppImage file, which did not exist for 0.6.80, the latest version there was 0.6.78, a little further down on the releases page. Sorry about that. I'd like to always publish for all versions, but each takes a while, so the Mac version will always be latest and Linux and Windows sometimes lagging by a few days when I don't have the time to wait, or run on battery or a subpar network. 

I just published the latest version for all platforms. Here's the file for Ubuntu:
**[meins-0.6.87-x86_64.AppImage](https://github.com/matthiasn/meins/releases/download/v0.6.87/meins-0.6.87-x86_64.AppImage)**

**Comment by yubrshen** [comment]
Thanks!
I'm really interested in it and looking forward to try your work.
