### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [matthiasn/meins#28]
https://github.com/matthiasn/meins/blob/4a70a0240848c3654d269a62a54b3700c16fab7c/electron-builder.yml#L24

Where can the AppImage be downloaded? I cannot seem to find it on the GitHub Releases page. Thanks.

**Comment by matthiasn** [comment]
Hi, under releases, but I don't build the AppImage on every release. The version from earlier this week has it: https://github.com/matthiasn/meins/releases/tag/v0.6.173

**Comment by probonopd** [comment]
Thank you.
